coverage:
  range: "50...100"
  ignore:          # files and folders that will be removed during processing
    - "src/**/tests"
    - "src/australianimagingservice_community/_version.py"
  status:
    project:
      default:
        threshold: "1"
    patch:
      default:
        target: 80
